
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfgsikugfeqdfpqxwrik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmZ3Npa3VnZmVxZGZwcXh3cmlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MDU2MDgsImV4cCI6MjA1Nzk4MTYwOH0.1IIVmP0ek5NqsfPziLKts5sWNeBBeotHvtswXFzXXzg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Helper types to make TypeScript happy with our tables that aren't in types.ts yet
export type Prescription = {
  id: string;
  patient_id: string;
  medicine_name: string;
  dosage: string;
  prescribed_by: string;
  created_at: string;
  updated_at: string;
  profile?: {
    name?: string;
    role?: string;
  } | null;
};

export type LabTest = {
  id: string;
  patient_id: string;
  test_name: string;
  results: string | null;
  status: 'Pending' | 'Completed';
  test_date: string;
  created_at: string;
  updated_at: string;
};

export type MedicalRecord = {
  id: string;
  patient_id: string;
  diagnosis: string;
  treatment: string | null;
  prescription: string | null;
  created_at: string;
  updated_at: string;
  created_by: string;
  profile?: {
    name?: string;
    role?: string;
  } | null;
};

export type Medication = {
  id: string;
  name: string;
  description: string | null;
  stock_level: number;
  unit: string;
  category: string | null;
  created_at: string;
  updated_at: string;
};

// Type-safe table names
export type TableName = 'appointments' | 'profiles' | 'patients' | 'lab_tests' | 'medical_records' | 'medications' | 'prescriptions';
